version: '3.4'

services:
  repititme.api:
    image: ${DOCKER_REGISTRY-}repititmeapi
    build:
      context: .
      dockerfile: RepititMe.Api/Dockerfile
    environment:
    ports:
      - "23400:80"
      - "23401:443"
    networks:
      - traefik_proxy



networks:
  traefik_proxy:
    external: true
