version: '3.4'

services:
  repititme.api:
    image: ${DOCKER_REGISTRY-}repititmeapi
    build:
      context: .
      dockerfile: RepititMe.Api/Dockerfile
    environment:
    # deploy bot
     #- BotToken=6835809808:AAG1QEjNLHBD6PxoB7c5n8TjVE9R-_rg_Qc
      # my bot 
      - BotToken=6133428642:AAEMRPIdInGzWRuvAcgf5jdOuDDzw6KEYCA
      - HostAddress=https://29dc-95-25-166-237.ngrok-free.app
      - DB_CS=host=95.163.230.58;port=5627;database=RepetitMe_Deploy;username=postgres;password=r2aWOf7qwLekkaz0;
      # - DB_CS=host=host.docker.internal;port=5627;database=RepetitMe_Deploy;username=postgres;password=98GerodoT98;
      - ReturnUrl=http://localhost:5173

      #- Secret_Key=live_-rCnmV7jENqXMuHUkjg8O4OiFe-s4gH59fjbTD1-dek
      #- Shop_Id=280065

      - Secret_Key=test_d9DrPcCuLU_69sq8QQDwMF4c0pIEoT9TEUR7f85QAgc
      - Shop_Id=289215
    ports:
      - "34000:80"
      - "34001:443"
    volumes:
      - ./wwwroot/media:/app/wwwroot/media
    networks:
      - traefik_proxy


networks:
  traefik_proxy:
    external: true
