version: '3.4'

services:
  repititme.api:
    image: ${DOCKER_REGISTRY-}repititmeapi
    build:
      context: .
      dockerfile: RepititMe.Api/Dockerfile
    environment:
      - BotToken=6133428642:AAEMRPIdInGzWRuvAcgf5jdOuDDzw6KEYCA
      - DB_CS=host=localhost;port=5627;database=Repitit;username=postgres;password=98GerodoT98;
      - HostAddress=https://ff0a-24-135-39-140.ngrok.io
      - HostAddress2=localhost
    ports:
      - "23400:80"
      - "23401:443"
    networks:
      - test-network

networks:
  test-network:
    external: true
